import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://demo-nova.singleinterface.com/login")
    page.get_by_role("textbox", name="Enter your email").click()
    page.get_by_role("textbox", name="Enter your email").fill("super_admin_hdfcLife@singleinterface.com")
    page.get_by_role("button", name="Sign In").click()
    page.get_by_role("textbox", name="Enter your email").dblclick()
    page.get_by_role("textbox", name="Enter your email").dblclick()
    page.get_by_role("textbox", name="Enter your email").dblclick()
    page.get_by_role("textbox", name="Enter your email").click()
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").press("ArrowRight")
    page.get_by_role("textbox", name="Enter your email").fill("")
    page.get_by_role("button", name="Sign In").click()
    page.get_by_role("textbox", name="Enter your email").click()
    page.get_by_role("textbox", name="Enter your email").fill("super_admin_hdfcLife@singleinterface.com")
    page.get_by_role("textbox", name="Enter your password").click()
    page.get_by_role("textbox", name="Enter your password").fill("password123")
    page.get_by_text("EmailEnter a valid emailPasswordEnter a valid PasswordForgot password?Sign In").click()
    page.get_by_text("EmailEnter a valid emailPasswordEnter a valid PasswordForgot password?Sign In").click()
    page.get_by_text("EmailEnter a valid emailPasswordEnter a valid PasswordForgot password?Sign In").click()
    page.get_by_text("EmailEnter a valid emailPasswordEnter a valid PasswordForgot password?Sign In").click()
    page.get_by_text("EmailEnter a valid emailPasswordEnter a valid PasswordForgot password?Sign In").click()
    page.get_by_text("EmailEnter a valid emailPasswordEnter a valid PasswordForgot password?Sign In").click()
    page.get_by_role("button", name="Sign In").click()
    page.get_by_text("EmailPasswordForgot password?").click()
    page.goto("https://demo-nova.singleinterface.com/dashboard-insight")
    page.get_by_role("button", name="Competitor AI").click()
    page.get_by_role("textbox", name="Search by name or address...").dblclick()
    page.get_by_role("button", name=" HDFC Life Insurance No 213").click()
    page.get_by_role("button", name=" Business Info").click()
    page.get_by_role("button", name=" Attributes").click()
    with page.expect_popup() as page1_info:
        page.get_by_role("row", name="Service Options   On-site").get_by_role("button").click()
    page1 = page1_info.value
    page1.close()
    page.get_by_role("link", name="Map Rank Tracker").click()
    page.get_by_role("button", name=" New Scan").click()
    page.get_by_role("textbox", name="Search by Name, Id, Address,").click()
    page.get_by_role("button", name="HDFC Life Insurance No 213,").click()
    page.get_by_role("textbox", name="Enter keyword").click()
    page.get_by_role("button", name="Car dealer prices ").click()
    page.get_by_role("button", name=" Scan Now").click()
    page.get_by_role("button", name="More Filters ").click()
    page.get_by_role("combobox").first.select_option("Delhi")
    page.get_by_role("button", name="Apply Filters").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
